"""Install the built wheel in isolation and exercise its public offline workflow."""

from __future__ import annotations

import json
import os

# Commands use fixed executable paths and argument vectors without a shell.
import subprocess  # nosec B404
import sys
import tempfile
import venv

# The parser receives only the bounded SVG generated by the installed package in this run.
import xml.etree.ElementTree as ET  # nosec B405
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def _run(command: list[str], *, cwd: Path, environment: dict[str, str]) -> str:
    # Every command is a fixed executable argument vector.
    completed = subprocess.run(  # nosec B603
        command,
        cwd=cwd,
        env=environment,
        check=False,
        capture_output=True,
        text=True,
        encoding="utf-8",
        timeout=120,
    )
    if completed.returncode != 0:
        raise RuntimeError(
            f"command failed ({completed.returncode}): {' '.join(command)}\n"
            f"stdout:\n{completed.stdout}\nstderr:\n{completed.stderr}"
        )
    return completed.stdout


def _executable(environment_dir: Path, name: str) -> Path:
    scripts = environment_dir / ("Scripts" if os.name == "nt" else "bin")
    suffix = ".exe" if os.name == "nt" else ""
    return scripts / f"{name}{suffix}"


def _write_portability_fixture(path: Path) -> None:
    records = (
        {
            "schema_version": "1.0",
            "trace_id": "trace-unicode",
            "step_id": "request",
            "timestamp": "2026-07-22T09:00:00Z",
            "operation_type": "request",
            "component": "запрос 🚀",
            "duration_ms": 2,
            "status": "ok",
        },
        {
            "schema_version": "1.0",
            "trace_id": "trace-unicode",
            "step_id": "outcome",
            "parent_step_id": "request",
            "timestamp": "2026-07-22T09:00:00.010Z",
            "operation_type": "outcome",
            "component": "réponse terminée",
            "duration_ms": 1,
            "status": "ok",
            "outcome": "success",
        },
    )
    # Write bytes so the fixture has CRLF line endings on every host, including Windows.
    payload = "\r\n".join(
        json.dumps(record, ensure_ascii=False, separators=(",", ":")) for record in records
    )
    path.write_bytes(f"{payload}\r\n".encode())


def _verify_native_cli_workflow(cli: Path, *, scratch: Path, environment: dict[str, str]) -> None:
    working_directory = scratch / "native path Юникод"
    working_directory.mkdir()
    input_path = working_directory / "trace input CRLF.jsonl"
    normalized_path = working_directory / "normalized résultat.jsonl"
    _write_portability_fixture(input_path)

    _run(
        [str(cli), "validate", str(input_path), "--normalized-out", str(normalized_path)],
        cwd=working_directory,
        environment=environment,
    )
    normalized = [
        json.loads(line)
        for line in normalized_path.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]
    if len(normalized) != 2 or normalized[-1].get("outcome") != "success":
        raise RuntimeError("installed CLI did not preserve the CRLF/Unicode validation input")

    first_output = working_directory / "report one"
    second_output = working_directory / "report two"
    for output in (first_output, second_output):
        _run(
            [str(cli), "analyze", str(input_path), "--output-dir", str(output)],
            cwd=working_directory,
            environment=environment,
        )

    artifacts = {"analysis.json", "normalized.jsonl", "report.html", "graph.svg"}
    for name in artifacts:
        first = first_output / name
        second = second_output / name
        if not first.is_file() or not second.is_file():
            raise RuntimeError(
                f"installed CLI did not create the expected analysis artifact: {name}"
            )
        if first.read_bytes() != second.read_bytes():
            raise RuntimeError(
                f"installed CLI produced non-deterministic analysis artifact: {name}"
            )

    analysis = json.loads((first_output / "analysis.json").read_text(encoding="utf-8"))
    if analysis.get("totals", {}).get("events") != 2:
        raise RuntimeError("installed CLI analysis did not include both portability events")
    ET.parse(first_output / "graph.svg")  # nosec B314
    html = (first_output / "report.html").read_text(encoding="utf-8")
    if "запрос 🚀" not in html or "réponse terminée" not in html:
        raise RuntimeError("installed CLI reports did not preserve Unicode labels")


def main() -> int:
    """Verify the newest wheel without editable or repository-relative imports."""

    wheels = sorted(
        (ROOT / "dist").glob("journeygraph-*.whl"), key=lambda path: path.stat().st_mtime
    )
    if not wheels:
        print("wheel verification error: dist/ contains no JourneyGraph wheel", file=sys.stderr)
        return 1
    wheel = wheels[-1]
    with tempfile.TemporaryDirectory(prefix="journeygraph-wheel-") as temporary:
        scratch = Path(temporary)
        environment_dir = scratch / "venv"
        venv.EnvBuilder(with_pip=True, clear=True, system_site_packages=False).create(
            environment_dir
        )
        python = _executable(environment_dir, "python")
        cli = _executable(environment_dir, "journeygraph")
        environment = os.environ.copy()
        for name in (
            "PYTHONHOME",
            "PYTHONPATH",
            "COVERAGE_PROCESS_START",
            "COV_CORE_SOURCE",
            "COV_CORE_CONFIG",
            "COV_CORE_DATAFILE",
        ):
            environment.pop(name, None)
        environment["PYTHONUTF8"] = "1"

        _run(
            [str(python), "-m", "pip", "install", "--no-deps", str(wheel)],
            cwd=scratch,
            environment=environment,
        )
        help_text = _run([str(cli), "--help"], cwd=scratch, environment=environment)
        if not all(command in help_text for command in ("validate", "analyze", "demo")):
            raise RuntimeError("installed CLI help is missing a public command")
        module_path = _run(
            [str(python), "-c", "import journeygraph; print(journeygraph.__file__)"],
            cwd=scratch,
            environment=environment,
        ).strip()
        if "site-packages" not in module_path:
            raise RuntimeError(f"wheel import did not resolve from site-packages: {module_path}")

        _verify_native_cli_workflow(cli, scratch=scratch, environment=environment)

        output = scratch / "demo"
        _run(
            [str(cli), "demo", "--output-dir", str(output)],
            cwd=scratch,
            environment=environment,
        )
        expected = {
            "analysis.json",
            "normalized.jsonl",
            "report.html",
            "graph.svg",
            "demo-traces.jsonl",
        }
        actual = {path.name for path in output.iterdir() if path.is_file()}
        if actual != expected:
            raise RuntimeError(
                f"installed demo artifacts differ: expected {expected}, got {actual}"
            )
        analysis = json.loads((output / "analysis.json").read_text(encoding="utf-8"))
        if analysis.get("schema_version") != "1.0" or analysis["totals"]["traces"] < 2:
            raise RuntimeError("installed demo analysis does not satisfy the public contract")
        # The file is bounded, local output generated immediately above.
        ET.parse(output / "graph.svg")  # nosec B314
        html = (output / "report.html").read_text(encoding="utf-8")
        if "Content-Security-Policy" not in html or "JourneyGraph" not in html:
            raise RuntimeError("installed demo HTML is incomplete")

    print(f"wheel smoke passed: {wheel.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
